# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: overlay.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'overlay.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roverlay.proto\x12\x07overlay\"\x0f\n\rHealthRequest\"\x1f\n\x0eHealthResponse\x12\r\n\x05ready\x18\x01 \x01(\x08\"\x98\x01\n\x0cOverlayFrame\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0f\n\x07job_key\x18\x02 \x01(\t\x12\x16\n\x0e\x63\x61ptured_at_ms\x18\x03 \x01(\x03\x12\'\n\nresolution\x18\x04 \x01(\x0b\x32\x13.overlay.Resolution\x12#\n\x05\x62oxes\x18\x05 \x03(\x0b\x32\x14.overlay.BoundingBox\"+\n\nResolution\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x9b\x01\n\x0b\x42oundingBox\x12\x10\n\x08track_id\x18\x01 \x01(\t\x12\x12\n\nclass_name\x18\x02 \x01(\t\x12\x12\n\nconfidence\x18\x03 \x01(\x01\x12\t\n\x01x\x18\x04 \x01(\x01\x12\t\n\x01y\x18\x05 \x01(\x01\x12\t\n\x01w\x18\x06 \x01(\x01\x12\t\n\x01h\x18\x07 \x01(\x01\x12\x12\n\nvelocity_x\x18\x08 \x01(\x01\x12\x12\n\nvelocity_y\x18\t \x01(\x01\"3\n\x0ePublishSummary\x12\x10\n\x08received\x18\x01 \x01(\x03\x12\x0f\n\x07\x64ropped\x18\x02 \x01(\x03\"\xd4\x01\n\x0e\x44\x65tectionEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\tcamera_id\x18\x02 \x01(\t\x12\x0f\n\x07job_key\x18\x03 \x01(\t\x12\x10\n\x08track_id\x18\x04 \x01(\t\x12\x12\n\nclass_name\x18\x05 \x01(\t\x12*\n\x04kind\x18\x06 \x01(\x0e\x32\x1c.overlay.DetectionEvent.Kind\x12\x16\n\x0eoccurred_at_ms\x18\x07 \x01(\x03\"\"\n\x04Kind\x12\t\n\x05START\x10\x00\x12\x06\n\x02IN\x10\x01\x12\x07\n\x03OUT\x10\x02\"\x1c\n\x08\x45ventAck\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x32\xc9\x01\n\rOverlayIngest\x12\x39\n\x06Health\x12\x16.overlay.HealthRequest\x1a\x17.overlay.HealthResponse\x12\x41\n\rPublishFrames\x12\x15.overlay.OverlayFrame\x1a\x17.overlay.PublishSummary(\x01\x12:\n\x0cPublishEvent\x12\x17.overlay.DetectionEvent\x1a\x11.overlay.EventAckB\x18\n\x14\x63om.visionos.overlayP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'overlay_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\024com.visionos.overlayP\001'
  _globals['_HEALTHREQUEST']._serialized_start=26
  _globals['_HEALTHREQUEST']._serialized_end=41
  _globals['_HEALTHRESPONSE']._serialized_start=43
  _globals['_HEALTHRESPONSE']._serialized_end=74
  _globals['_OVERLAYFRAME']._serialized_start=77
  _globals['_OVERLAYFRAME']._serialized_end=229
  _globals['_RESOLUTION']._serialized_start=231
  _globals['_RESOLUTION']._serialized_end=274
  _globals['_BOUNDINGBOX']._serialized_start=277
  _globals['_BOUNDINGBOX']._serialized_end=432
  _globals['_PUBLISHSUMMARY']._serialized_start=434
  _globals['_PUBLISHSUMMARY']._serialized_end=485
  _globals['_DETECTIONEVENT']._serialized_start=488
  _globals['_DETECTIONEVENT']._serialized_end=700
  _globals['_DETECTIONEVENT_KIND']._serialized_start=666
  _globals['_DETECTIONEVENT_KIND']._serialized_end=700
  _globals['_EVENTACK']._serialized_start=702
  _globals['_EVENTACK']._serialized_end=730
  _globals['_OVERLAYINGEST']._serialized_start=733
  _globals['_OVERLAYINGEST']._serialized_end=934
# @@protoc_insertion_point(module_scope)
