# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import overlay_pb2 as overlay__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in overlay_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OverlayIngestStub:
    """---------------------------------------------------------------------------
    OverlayIngest — Backend implement, AI Service gọi
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/overlay.OverlayIngest/Health',
                request_serializer=overlay__pb2.HealthRequest.SerializeToString,
                response_deserializer=overlay__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.PublishFrames = channel.stream_unary(
                '/overlay.OverlayIngest/PublishFrames',
                request_serializer=overlay__pb2.OverlayFrame.SerializeToString,
                response_deserializer=overlay__pb2.PublishSummary.FromString,
                _registered_method=True)
        self.PublishEvent = channel.unary_unary(
                '/overlay.OverlayIngest/PublishEvent',
                request_serializer=overlay__pb2.DetectionEvent.SerializeToString,
                response_deserializer=overlay__pb2.EventAck.FromString,
                _registered_method=True)


class OverlayIngestServicer:
    """---------------------------------------------------------------------------
    OverlayIngest — Backend implement, AI Service gọi
    ---------------------------------------------------------------------------
    """

    def Health(self, request, context):
        """Health check — AI Service chờ Backend sẵn sàng
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishFrames(self, request_iterator, context):
        """Bbox stream — 1 stream duy nhất cho toàn tiến trình, cho phép mất
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvent(self, request, context):
        """Sự kiện đếm — unary, không được mất, có ack
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OverlayIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=overlay__pb2.HealthRequest.FromString,
                    response_serializer=overlay__pb2.HealthResponse.SerializeToString,
            ),
            'PublishFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishFrames,
                    request_deserializer=overlay__pb2.OverlayFrame.FromString,
                    response_serializer=overlay__pb2.PublishSummary.SerializeToString,
            ),
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=overlay__pb2.DetectionEvent.FromString,
                    response_serializer=overlay__pb2.EventAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'overlay.OverlayIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('overlay.OverlayIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OverlayIngest:
    """---------------------------------------------------------------------------
    OverlayIngest — Backend implement, AI Service gọi
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/overlay.OverlayIngest/Health',
            overlay__pb2.HealthRequest.SerializeToString,
            overlay__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/overlay.OverlayIngest/PublishFrames',
            overlay__pb2.OverlayFrame.SerializeToString,
            overlay__pb2.PublishSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/overlay.OverlayIngest/PublishEvent',
            overlay__pb2.DetectionEvent.SerializeToString,
            overlay__pb2.EventAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
